### ISSUE TITLE
einvoice and Odoo

### ISSUE THREAD

**Issue by aduijs** [dpalominop/eInvoice#1]
Hello @dpalominop ,
I noticed you have experience with odoo/openerp as well
would this webservice be easy to incorporate in odoo?

**Comment by dpalominop** [comment]
Hello @aduijs, 
yes it can be implemented, but you must use background jobs in each query towards the final web service.
Are you interested in implementing it?

**Comment by aduijs** [comment]
Hi @dpalominop,Yes i am interested in implementing it in my Odoo 10
environment.
So far from what i could find your code is somewhat the closest to be
fitted into Odoo.
Are there any good explications about the sunat webservice?
any suggestions?



2017-07-11 12:04 GMT-05:00 Daniel Palomino <notifications@github.com>:
